### PR TITLE
Support follow ups

### PR DESCRIPTION
**Pull request by IsaackMwenda**

### CODE REVIEW

**Comment by lukechurch** [comment]
@IsaackMwenda please separate this into two PRs, one for Coda changes and the other that incluses the source changes

**Review by lukechurch — CHANGES_REQUESTED** [review]
As discussed, please separate

**Comment by IsaackMwenda** [comment]
@lukechurch merged, please look again

**Review by lukechurch — APPROVED** [review]
Thanks @IsaackMwenda

**Pull request merged**
